'use server';
/**
 * @fileOverview Nexvoro AI D-ID Avatar Service.
 * Provides modular access to D-ID Talks API for neural avatar synthesis.
 * Ingests text from Gemini and synchronizes it with high-fidelity visual nodes.
 */

const DID_API_KEY = process.env.DID_API_KEY;

export type DidStatusResponse = {
  success: boolean;
  status?: 'created' | 'started' | 'done' | 'error';
  videoUrl?: string;
  error?: string;
};

/**
 * Initiates a new neural talk session.
 * @param text The text generated by Gemini to be spoken.
 * @param sourceUrl The publicly accessible image URL for the avatar.
 */
export async function createTalk(text: string, sourceUrl: string) {
  if (!DID_API_KEY) {
    console.warn("[D-ID] API Key missing. Service entering bypass mode.");
    return { success: false, error: "D-ID API key not configured." };
  }

  try {
    const response = await fetch('https://api.d-id.com/talks', {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${Buffer.from(DID_API_KEY + ':').toString('base64')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        source_url: sourceUrl,
        script: {
          type: 'text',
          input: text,
          provider: { type: 'microsoft', voice_id: 'en-US-GuyNeural' }, // Senior Partner Persona
        },
        config: {
          fluent: true,
          pad_audio: 0.0,
          driver_expressions: {
            expressions: [{ expression: 'serious', start_frame: 0 }]
          }
        },
      }),
    });

    const data = await response.json();
    if (!data.id) throw new Error(data.message || "Failed to initialize neural talk.");

    return { success: true, talkId: data.id };
  } catch (error: any) {
    console.error("[D-ID] Creation Failed:", error);
    return { success: false, error: error.message };
  }
}

/**
 * Checks the status of a specific neural talk node.
 */
export async function getTalkStatus(talkId: string): Promise<DidStatusResponse> {
  if (!DID_API_KEY) return { success: false, error: "D-ID API key missing." };

  try {
    const response = await fetch(`https://api.d-id.com/talks/${talkId}`, {
      headers: {
        'Authorization': `Basic ${Buffer.from(DID_API_KEY + ':').toString('base64')}`,
      },
    });

    const data = await response.json();
    return {
      success: true,
      status: data.status,
      videoUrl: data.result_url,
    };
  } catch (error: any) {
    console.error("[D-ID] Status Check Failed:", error);
    return { success: false, error: error.message };
  }
}
